### ISSUE TITLE
LightIngest seems to require .NET 6 unlike what's stated in the documentation

### ISSUE THREAD

**Issue by miguelcrpinto** [Azure/Kusto-Lightingest#13]
**Describe the bug**
In the [LightIngest documentation](https://learn.microsoft.com/en-us/azure/data-explorer/lightingest#prerequisites) it is stated that if you use it as a .NET tool, it requires that you have the .NET SDK version 6.0 or higher installed on your machine.

It doesn't seem to be the case as you cannot run the LightIngest installed as .NET tool when you solely have .NET 8 installed. 

I tried installing LightIngest as a .NET tool in Azure DevOps and I got the following error:

![Image](https://github.com/user-attachments/assets/ea7ee453-5a1b-4692-a649-530ccf9a5708)

**Exception or Stack Trace**
![Image](https://github.com/user-attachments/assets/ea7ee453-5a1b-4692-a649-530ccf9a5708)

**To Reproduce**
**In Azure DevOps**:
Create a pipeline that has the following tasks

1.  UseDotNet@2 with version 8.x
2.  DotNetCoreCLI@2 with command "custom", custom "tool" and arguments "install -g Microsoft.Azure.Kusto.LightIngest"
3.  Script task that only executes "LightIngest"

On a windows laptop that only has .NET 8 installed:

1. Open a terminal (powershell or windows)
2. run the command: dotnet tool install -g Microsoft.Azure.Kusto.LightIngest
3. run the command: LightIngest

**Expected behavior**
From what is stated in the documentation, it would be expected that LightIngest could be ran while having only .NET 8 installed (and not .NET 6)

**Screenshots**
![Image](https://github.com/user-attachments/assets/ea7ee453-5a1b-4692-a649-530ccf9a5708)

**Setup (please complete the following information):**
 - .NET SDK Version: .NET 8 (only .NET 8 installed)
 - LightIngest Version: 12.2.6 (and possibly previous versions)
 - Tool source: dotnet tool install

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup Information Added

**Comment by ohadbitt** [comment]
Locally did not reproduce 
dotnet --list-sdks
8.0.403 [C:\Program Files\dotnet\sdk]

**Comment by miguelcrpinto** [comment]
@ohadbitt if I'm not mistaken, you only need the .Net 6 runtime and not the SDK. You probably have the .NET 6 runtime installed

**Comment by ohadbitt** [comment]
@miguelcrpinto  You are right, so we still did not state it wrongly :)
Anyway - A new version will be released with the support of .net 6 runtime

**Comment by ohadbitt** [comment]
Version 12.3.0 released with both frameworks
