### ISSUE TITLE
LightIngest Will Run Until The Computer Runs Out Of Memory

### ISSUE THREAD

**Issue by TheTman7** [Azure/Kusto-Lightingest#6]
**Description:**
During a LightIngest call with over 3.3 million parquet files and 800gb of compressed data, the LightIngest utility's memory continuously grew. This only appears to happen when items are being discovered. Once all of the items have been discovered and items are being filtered and ingested, the memory stays the same.

**Reproduction:**
1. Store millions of parquet files in an Azure storage account (the parquet files I stored were under 1mb compressed).
2. Ingest the files into ADX.
3. Note the memory increasing the entire time.

**Expected:**
As a user, I would expect the memory to be capped, have an option for a cap, or for it to release some memory at some point instead of going up the entire time.

Note: Millions of files may seem unnecessary, but when you have data in ADX that goes back to before the 2000's, there can be a lot of files from the continuous export that may need to be ingested at some point (either as a backup or somewhere else).

**Comment by ohadbitt** [comment]
Hi
Thank you for opening this issue - i'm working on some solution

**Comment by TheTman7** [comment]
The issue appears to be resolved! Thanks!
